// Mock data for ADONIS AI Platform

export const dashboardMetrics = {
  videosGenerated: 1247,
  viralScore: 87.4,
  potentialLeads: 3892,
  totalReach: 2840000,
  conversion: 4.7,
  aiEfficiency: 94.2,
  revenueForecast: 8400000,
  videosChange: +23,
  leadsChange: +18,
  reachChange: +34,
};

export const revenueChartData = [
  { month: "Янв", revenue: 420000, leads: 124, videos: 48 },
  { month: "Фев", revenue: 580000, leads: 167, videos: 72 },
  { month: "Мар", revenue: 720000, leads: 198, videos: 89 },
  { month: "Апр", revenue: 940000, leads: 267, videos: 114 },
  { month: "Май", revenue: 1100000, leads: 312, videos: 134 },
  { month: "Июн", revenue: 1380000, leads: 389, videos: 156 },
  { month: "Июл", revenue: 1650000, leads: 445, videos: 178 },
  { month: "Авг", revenue: 2100000, leads: 567, videos: 203 },
  { month: "Сен", revenue: 2480000, leads: 634, videos: 231 },
  { month: "Окт", revenue: 3200000, leads: 789, videos: 267 },
  { month: "Ноя", revenue: 4100000, leads: 934, videos: 312 },
  { month: "Дек", revenue: 5800000, leads: 1247, videos: 398 },
];

export const platformReachData = [
  { platform: "TikTok", reach: 1240000, videos: 487, color: "#fe2c55" },
  { platform: "Instagram", reach: 890000, videos: 312, color: "#e91e8c" },
  { platform: "YouTube", reach: 456000, videos: 198, color: "#ff0000" },
  { platform: "VK", reach: 178000, videos: 134, color: "#0077ff" },
  { platform: "Telegram", reach: 76000, videos: 116, color: "#26a5e4" },
];

export const trendingTopics = [
  {
    id: 1,
    title: "Почему я ушёл из найма в 2026",
    viralScore: 96,
    views: 4200000,
    engagement: 8.4,
    trend: "🔥 Горячий",
    category: "Уход из найма",
    hooks: ["Я работал 8 лет на дядю...", "Мой последний рабочий день был...", "Вот сколько я зарабатывал в найме vs сейчас"],
    growth: +234,
  },
  {
    id: 2,
    title: "Сколько приносит бизнес на печати на одежде",
    viralScore: 94,
    views: 3800000,
    engagement: 7.9,
    trend: "📈 Растёт",
    category: "Доходы бизнеса",
    hooks: ["Открыл бизнес на печати с 0 рублей...", "Показываю реальную выручку за месяц...", "Почему печать на одежде — золотая жила"],
    growth: +187,
  },
  {
    id: 3,
    title: "Как открыть ИП за 1 день — полная инструкция",
    viralScore: 91,
    views: 2900000,
    engagement: 6.8,
    trend: "⚡ Стабильный",
    category: "Открытие бизнеса",
    hooks: ["Госуслуги, МФЦ или онлайн?", "Налоги для ИП в 2026 — что выбрать", "Ошибки при открытии ИП"],
    growth: +143,
  },
  {
    id: 4,
    title: "Франшиза или свой бренд — что выгоднее",
    viralScore: 89,
    views: 2400000,
    engagement: 6.2,
    trend: "🚀 Взлёт",
    category: "Франчайзинг",
    hooks: ["Посчитал реальные цифры...", "Через 6 месяцев я окупил вложения...", "Почему не стоит начинать с нуля"],
    growth: +198,
  },
  {
    id: 5,
    title: "Бизнес с нуля — мои первые 300.000 в месяц",
    viralScore: 88,
    views: 2100000,
    engagement: 5.9,
    trend: "🔥 Горячий",
    category: "Доходы",
    hooks: ["Стартовый капитал был всего...", "Первый клиент пришёл через...", "Масштабирование с 30к до 300к"],
    growth: +167,
  },
  {
    id: 6,
    title: "Мерч-бизнес: как зарабатывать на печати",
    viralScore: 86,
    views: 1800000,
    engagement: 5.4,
    trend: "📈 Растёт",
    category: "Мерч",
    hooks: ["DTF, шелкография или сублимация?", "Мои клиенты платят по...", "Как найти первых заказчиков"],
    growth: +134,
  },
];

export const videoQueue = [
  {
    id: 1,
    title: "Как открыть франшизу ADONIS за 30 дней",
    status: "rendering",
    progress: 73,
    platform: ["TikTok", "Instagram"],
    duration: "0:47",
    thumbnail: null,
    viralScore: 91,
    eta: "2 мин",
  },
  {
    id: 2,
    title: "Доход партнёра ADONIS — реальные цифры",
    status: "rendering",
    progress: 45,
    platform: ["YouTube", "TikTok"],
    duration: "1:12",
    thumbnail: null,
    viralScore: 89,
    eta: "5 мин",
  },
  {
    id: 3,
    title: "Производство мерча с нуля — как это работает",
    status: "queued",
    progress: 0,
    platform: ["Instagram"],
    duration: "0:58",
    thumbnail: null,
    viralScore: 87,
    eta: "12 мин",
  },
  {
    id: 4,
    title: "Почему уходят из найма в производство",
    status: "completed",
    progress: 100,
    platform: ["TikTok", "VK"],
    duration: "0:52",
    thumbnail: null,
    viralScore: 94,
    eta: "Готово",
  },
  {
    id: 5,
    title: "Франшиза vs свой бренд — честный разбор",
    status: "completed",
    progress: 100,
    platform: ["Instagram", "YouTube"],
    duration: "1:04",
    thumbnail: null,
    viralScore: 88,
    eta: "Готово",
  },
];

export const aiActivityFeed = [
  { id: 1, time: "только что", action: "Сгенерировал сценарий", detail: "«Как выйти на 500к в месяц»", type: "generate" },
  { id: 2, time: "2 мин назад", action: "Опубликован ролик", detail: "TikTok — 12.4K просмотров за час", type: "post" },
  { id: 3, time: "5 мин назад", action: "AI анализ трендов", detail: "Обнаружен новый тренд: «Налоги 2026»", type: "analyze" },
  { id: 4, time: "8 мин назад", action: "Новый лид", detail: "Заявка на франшизу из Instagram", type: "lead" },
  { id: 5, time: "12 мин назад", action: "Завершён рендер", detail: "«Мой первый бизнес с 50к» — готово", type: "render" },
  { id: 6, time: "18 мин назад", action: "Viral Score обновлён", detail: "Ролик набрал 94 балла вирусности", type: "viral" },
];

export const scriptTemplates = [
  {
    id: 1,
    category: "Уход из найма",
    title: "История трансформации",
    hook: "Я работал менеджером 5 лет и зарабатывал 80к в месяц. Теперь — смотрите...",
    body: "Покажи реальные цифры. Сравни жизнь в найме vs свой бизнес. Конкретные шаги.",
    cta: "Хочешь так же? Напиши «СТАРТ» в директ",
    duration: "45-60 сек",
    viralScore: 91,
  },
  {
    id: 2,
    category: "Франчайзинг",
    title: "Разбор франшизы ADONIS",
    hook: "Вложил X рублей — получаю Y в месяц. Реальные цифры партнёра ADONIS",
    body: "Формат бизнеса, вложения, сроки окупаемости. Интервью с партнёром.",
    cta: "Хочешь так же? Ссылка в описании →",
    duration: "60-90 сек",
    viralScore: 89,
  },
  {
    id: 3,
    category: "Производство",
    title: "За кулисами производства",
    hook: "Как мы печатаем 500+ изделий в день — показываю изнутри",
    body: "Оборудование, процессы, команда. Цифры и факты.",
    cta: "Хочешь свой бизнес на производстве?",
    duration: "30-45 сек",
    viralScore: 87,
  },
];

export const autopostSchedule = [
  { id: 1, platform: "TikTok", time: "09:00", title: "Как я зарабатываю на мерче", status: "scheduled", date: "Сегодня" },
  { id: 2, platform: "Instagram", time: "12:00", title: "3 причины открыть франшизу", status: "scheduled", date: "Сегодня" },
  { id: 3, platform: "YouTube", time: "17:00", title: "Полный разбор бизнеса ADONIS", status: "processing", date: "Сегодня" },
  { id: 4, platform: "TikTok", time: "20:00", title: "День из жизни партнёра", status: "draft", date: "Завтра" },
  { id: 5, platform: "VK", time: "11:00", title: "Производство мерча изнутри", status: "draft", date: "Завтра" },
  { id: 6, platform: "Telegram", time: "14:00", title: "Кейс: 300к за 3 месяца", status: "draft", date: "Завтра" },
];

export const analyticsData = {
  weeklyViews: [
    { day: "Пн", views: 124000, leads: 34 },
    { day: "Вт", views: 189000, leads: 52 },
    { day: "Ср", views: 156000, leads: 41 },
    { day: "Чт", views: 234000, leads: 67 },
    { day: "Пт", views: 298000, leads: 89 },
    { day: "Сб", views: 412000, leads: 123 },
    { day: "Вс", views: 367000, leads: 108 },
  ],
  topVideos: [
    { title: "Уход из найма — мой опыт", views: 2400000, likes: 187000, leads: 234 },
    { title: "Бизнес на печати с нуля", views: 1890000, likes: 143000, leads: 198 },
    { title: "Сколько стоит франшиза", views: 1560000, likes: 98000, leads: 167 },
  ],
};
